repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.0
    hooks:
      - id: ruff
        name: ruff (linting)
        args: [--fix]
        types_or: [python, pyi]
        stages: [pre-commit]
        fail_fast: true
        verbose: true

  - repo: local
    hooks:
      - id: ty
        name: ty (type checking)
        entry: uvx ty check
        language: system
        types: [python]
        pass_filenames: true
        fail_fast: true
        verbose: true